version: "3"
services:
    segment:
        # restart: always
        build: /Users/user/projects/bigData/spark/geoFusion/api-segment/project
        # volumes:
        #     - ${PROJECT_PATH}/segment/:/opt/app
        #     - /Users/user/projects/bigData/spark/geoFusion/api-segment/project/:/opt/app
        ports:
            - "8000:8082"
        # env_file:
        #     - ./docker-base.env
        environment:
            - DJANGO_SETTINGS_MODULE=project.settings
            - VIRTUAL_HOST=0.0.0.0
            - VIRTUAL_PORT=8000
        links:
            - "mongodb:mongodb"
            - "postgres:postgres"
            # - memcached_host
            # - redis_host
            # - elasticsearch_host
        # depends_on:
        #     - mongodb
        #     - postgres
        # networks:
        #     frontend-apis:
        #     aliases:
        #         - backend.app_painel.local
        # default:
        #     certs:
        #     nginx-log:
    postgres:
        image: postgres:9.6
        # volumes:
            # - "./data:/var/lib/postgresql/data"
        environment:
            - POSTGRES_USER=segment
            - POSTGRES_DB=segment
            - POSTGRES_PASSWORD=segment
        ports:
            - "5432:5432"
    mongodb:
        image: mongo:latest
        # container_name: "mongodb"
        # environment:
        #   - MONGO_DATA_DIR=/data
        #   - MONGO_LOG_DIR=/dev/null
        # volumes:
        #   - ./data/db:/data/db
        ports:
            - 27017:27017
        # command: mongod --dbpath --smallfiles --logpath=/dev/null # --quiet
        environment:
            - MONGODB_USER="segment" 
            - MONGODB_PASS="segment"