# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-29 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('codigo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nome', models.TextField()),
                ('municipio', models.TextField()),
                ('uf', models.TextField()),
                ('area', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Concorrente',
            fields=[
                ('codigo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nome', models.TextField(blank=True, null=True)),
                ('categoria', models.TextField(blank=True, null=True)),
                ('faixa_preco', models.TextField(blank=True, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('municipio', models.TextField(blank=True, null=True)),
                ('uf', models.TextField(blank=True, null=True)),
                ('codigo_bairro', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
