from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.contrib import admin

from app.views import ToolViewSet, AuthorViewSet, BookViewSet, index_view, BairroViewSet, ConcorrenteViewSet, BairroMongoViewSet
from users.views import *

from project.routers import HybridRouter

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

# We use a single global DRF Router that routes views from all apps in project
router = HybridRouter()

# app views and viewsets
router.register(r'tool', ToolViewSet, r"tool")
router.register(r'author', AuthorViewSet, r"author")
router.register(r'book', BookViewSet, r"book")
router.register(r'user', UserViewSet, r"user")

# router.register(r'talks-mongo', TalkMongoViewSet, r"talks-mongo")

router.register(r'bairro-mongo', BairroMongoViewSet, r"bairro-mongo")

router.register(r'bairro', BairroViewSet)
router.register(r'concorrente', ConcorrenteViewSet)


router.add_api_view(r'auth', url(r'^auth/$', ObtainAuthToken.as_view(), name=r"auth"))


urlpatterns = [
    # default django admin interface (currently unused)
    url(r'^admin/', admin.site.urls),

    # root view of our REST api, generated by Django REST Framework's router
    url(r'^api/', include(router.urls, namespace='api')),

    # index page should be served by django to set cookies, headers etc.
    url(r'^$', index_view, {}, name='index'),
]

# let django built-in server serve static and media content
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
